// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '451468018906',
    projectId: 'homeblend-f39f9',
    authDomain: 'homeblend-f39f9.firebaseapp.com',
    storageBucket: 'homeblend-f39f9.firebasestorage.app',
    measurementId: 'G-YT3443ZVEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '451468018906',
    projectId: 'homeblend-f39f9',
    storageBucket: 'homeblend-f39f9.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '451468018906',
    projectId: 'homeblend-f39f9',
    storageBucket: 'homeblend-f39f9.firebasestorage.app',
    androidClientId: '451468018906-jshdbftkoaqqc6oibmqc8imp2qrj55a2.apps.googleusercontent.com',
    iosClientId: '451468018906-s242k3aa3k8rs37boj2m5j7mfg1vl7mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeblend',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '451468018906',
    projectId: 'homeblend-f39f9',
    storageBucket: 'homeblend-f39f9.firebasestorage.app',
    androidClientId: '451468018906-jshdbftkoaqqc6oibmqc8imp2qrj55a2.apps.googleusercontent.com',
    iosClientId: '451468018906-s242k3aa3k8rs37boj2m5j7mfg1vl7mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeblend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '451468018906',
    projectId: 'homeblend-f39f9',
    authDomain: 'homeblend-f39f9.firebaseapp.com',
    storageBucket: 'homeblend-f39f9.firebasestorage.app',
    measurementId: 'G-7BFDB9K3SJ',
  );

}
